spring:
  #该参数用来开启重试机制  
  cloud:
    loadbalancer:
      retry:
        enabled: true

  redis:
    host: 192.168.2.110
    port: 6379

  #druid datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.110:3306/mmall?characterEncoding=utf-8
    username: xrj
    password: 123456
    
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 100
      filters:  stat,wall,log4j      

eureka:
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/