logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    org.apache: INFO
    o.a.k.clients.consumer: DEBUG
              
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB